import type { Metadata } from "next";
import { Cabin, Fragment_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/libs/utils";
import { Navbar } from "./Navbar";
import { Footer } from "./Footer";

const sans = Cabin({ subsets: ["latin"], variable: "--font-sans" });
const mono = Fragment_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans", sans.variable, mono.variable)}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
